#!/usr/bin/expect -f

set myname [lindex $argv 0] 
set mytopic [lindex $argv 1]
spawn ./questions
 
expect "Hello, who are you?\r"
 
send -- "Im $myname\r"
 
expect "Can I ask you some questions?\r"
 
send -- "Sure\r"
 
expect "What is your favorite topic?\r"
 
send -- "$mytopic\r"
 
expect eof
